apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: capg-pathtoprod-controlplane-0
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "capg-pathtoprod"
spec:
  version: v1.15.3
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: capg-pathtoprod-controlplane-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPMachine
    name: capg-pathtoprod-controlplane-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPMachine
metadata:
  name: capg-pathtoprod-controlplane-0
spec:
  instanceType: n1-standard-2
  zone: us-central1-a
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: capg-pathtoprod-controlplane-0
spec:
  # For more information about these values,
  # refer to the Kubeadm Bootstrap Provider documentation.
  initConfiguration:
    nodeRegistration:
      name: '{{ ds.meta_data.hostname }}'
      kubeletExtraArgs:
        cloud-provider: gce
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: gce
    controllerManager:
      extraArgs:
        cloud-provider: gce
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  name: capg-pathtoprod-worker
  labels:
    cluster.x-k8s.io/cluster-name: capg-pathtoprod
    # Labels beyond this point are for example purposes,
    # feel free to add more or change with something more meaningful.
    # Sync these values with spec.selector.matchLabels and spec.template.metadata.labels.
    nodepool: nodepool-0
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capg-pathtoprod
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: capg-pathtoprod
        nodepool: nodepool-0
    spec:
      version: v1.15.3
      bootstrap:
        configRef:
          name: capg-pathtoprod-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: capg-pathtoprod-worker
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: GCPMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPMachineTemplate
metadata:
  name: capg-pathtoprod-worker
spec:
  template:
    spec:
      instanceType: n1-standard-2
      zone: us-central1-a
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfigTemplate
metadata:
  name: capg-pathtoprod-worker
spec:
  template:
    spec:
      # For more information about these values,
      # refer to the Kubeadm Bootstrap Provider documentation.
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.hostname }}'
          kubeletExtraArgs:
            cloud-provider: gce
```
