apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capg-pathtoprod
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPCluster
    name: pathtoprod-dev
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPCluster
metadata:
  name: capg-pathtoprod
spec:
  project: capg-pathtoprod
  region: us-central1
---
