apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capg-pathtoprod
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.128.0.0/20
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: GCPCluster
    name: capg-pathtoprod
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: GCPCluster
metadata:
  name: capg-pathtoprod
spec:
  project: ivory-voyage-267519
  region: us-central1
---
