apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capa-pathtoprod
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: pathtoprod
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capa-pathtoprod-controlplane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: capa-pathtoprod
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: capa-pathtoprod
  namespace: default
spec:
  region: ca-central-1
  sshKeyName: default
  # TODO configure non managed vpc
  # networkSpec:
    # Managed VPC includes 1 public and 1 private subnet, an Internet Gateway & a NAT gateway
    # subnets:
    #   - cidrBlock: 10.128.0.0/20
    # vpc:
    #   id: vpc-c72167af
    # subnets:
    #   - cidrBlock: 10.128.0.0/20
---